import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  useQuery,
  useMutation,
  useQueryClient,
  QueryClient,
  QueryClientProvider,
} from "react-query";
import { ApolloClient, InMemoryCache, gql } from "@apollo/client";
import { useRouter } from "next/router";

const client = new ApolloClient({
  uri: "http://localhost:3000/api/graphql",
  cache: new InMemoryCache(),
});

export default function Home(props) {
  const router = useRouter();

  // Queries;
  const query = useQuery("users", async () => {
    const { data } = await client.query({
      query: gql`
        query {
          users {
            name
          }
        }
      `,
    });

    const users = data.users;
    return users;
  });
  console.log("querry", query);

  if (query.status === "loading") {
    return <h2>Loading.....</h2>;
  }

  if (query.status === "error") {
    console.log("error", query.error);
    // router.push("/error");
  }

  if (query.status === "success") {
    return (
      <div className={styles.container}>
        <Image
          src="https://images.unsplash.com/photo-1621609764095-b32bbe35cf3a?ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=80"
          width={300}
          height={400}
          alt="hmm"
        />
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">SpaceX</a>
          </h1>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    );
  }
}

export async function getStaticProps() {
  // Code will go here
  let users = [];
  try {
    const { data } = await client.query({
      query: gql`
        query {
          users {
            name
          }
        }
      `,
    });

    users = data.users;
  } catch (error) {
    console.log("Indexjs error: ", error);
  }

  return {
    props: {
      users,
    },
  };
}
